Use faf-java-api and clean up/reformat code
FAForever/website pull request #141
Opened 2018-05-18 09:21 UTC by micheljung

2018-05-18 10:14 UTC, Brutus5000 requested changes
The reset password needs to be considered. We have a semantic change. Against python-api you need to give username and email. In java-api this is merged into one "identifier" (can be either email or username)

https://github.com/FAForever/faf-java-api/blob/develop/src/main/java/com/faforever/api/user/UsersController.java#L91

Description and form fields need to be changed:
https://github.com/FAForever/website/blob/feature/java-api/templates/views/account/resetPassword.pug#L10
API route needs to be changed to camel case and use identifier
https://github.com/FAForever/website/blob/ea6614ce2bdf26ba9ab21c69998cf004ef0ce29b/routes/views/accounts/post/resetPassword.js#L46

2018-05-18 14:20 UTC, Brutus5000 approved these changes
From API side everything seems to be migrated now.

2018-05-18 22:22 UTC, Brutus5000 commented
I have successfully tested registration, username change, email change, password change and steam linking on the test server.

2018-05-19 16:57 UTC, Sheeo approved these changes
Overall looks good, I trust that it works from Brutus' testing.

Moving forward there's definitely more cleanup to do, though. And in general, please do separate whitespace changes and semantic ones into more commits (Even thought github now has an option to ignore it, you'd still like to be able to verify it separately).

2018-05-19 16:57 UTC, Sheeo commented on express.js
> +	immutable: true,
This whitespace seems to have been exchanged with tabs?

2018-05-19 16:57 UTC, Sheeo commented on express.js
> +let expressValidator = require('express-validator');
Since we're targeting node 9+, it's safe to use `const` -- best do so for `require`s.

2018-05-19 22:16 UTC, merged