Clan app
FAForever/website pull request #200
Opened 2019-09-20 19:02 UTC by Rackover

Replacement for the clan app

2019-09-22 12:16 UTC, Rackover commented
The app has been thoroughly tested by a few people (Resistance, Samuel, Brutus, PhilipJFry, Blackheart, and more) and all errors / issues that arose have been solved. It's working fully and has feature parity for the legacy clan app. 

Ready for deployment.

2019-09-28 10:18 UTC, Brutus5000 requested changes
Just some minor stuff

2019-09-28 10:18 UTC, Brutus5000 commented on public/js/app/browse_clans.js
> +        const splitClan = [components.shift(), components.join(' ')];
It is not easy to read kind of input you expect here. Please add comments with examples.

2019-09-28 10:18 UTC, Brutus5000 commented on .env.example
> +PLAYER_COUNT_UPDATE_INTERVAL = 3            # 3 seconds
Please add newline at the end.

2019-09-28 10:18 UTC, Brutus5000 commented on templates/views/clans/browse.pug
> +  script(src="/js/browse_clans.min.js")
Newline at the end

2019-09-28 10:18 UTC, Brutus5000 commented on routes/views/clans/post/create.js
> +  req.checkBody('clan_name', "Please indicate your clan's name").notEmpty().isLength({ max: 64 });
Just checked the db, max clan name there is 40

2019-10-06 18:56 UTC, merged