Fix favorite faction display
FAForever/website pull request #218
Opened 2020-01-21 07:48 UTC by Syldarion

These changes include a fix to the favorite faction display and an update to the formatting of the changed file. I'll remove the latter if it isn't wanted, it was just to make working on it easier.

The favorite faction fix is explained in the second commit message.

2020-01-21 13:32 UTC, Brutus5000 requested changes
Generally I don't have a problem with your code, but given the fact that we recently spent multiple hours debugging performance issues of this application I cannot accept 3 nested for loops inside a while loop.

We need to find better data structures for this.

2020-01-21 17:10 UTC, Syldarion commented
For sure, I'll take another stab at this then.

2020-01-21 21:12 UTC, norraxx commented
@Syldarion Maybe, we could talk about this code at discord. You would explain what you want to achieve, and I'd say what I don't like on this commit, what do you think?

2020-01-22 02:33 UTC, Syldarion commented
@norraxx Basically, just trying to have favorite faction percentage based off all games rather than those found first. I can see how just re-using a nested for loop is undesirable, seeing as it'll be going through the same data and processing it the same way twice.

2020-01-22 10:53 UTC, norraxx commented
@Syldarion Imagine how much load you have to do, to just compute that stuff. As I said, let's talk about that problem on discord https://discord.gg/VYX25M.
Write me there, i'm `dragonite` user there, maybe we can figure how to make it better. As @Brutus5000 said your solution will make very big load on servers, web page will start minutes, and maybe you won't have enough memory, and what you want is compute 4 numbers. :-)

2020-01-24 05:02 UTC, Syldarion commented
@norraxx I spent some time trying to come up with a better solution, but only managed to find either longer runtime or wrong data.
I'd ask that you try the change yourself. Locally, running with this change is within a couple seconds of the runtime of what is live, but comes with accurate data.
Or I could close this and open an issue.

2020-01-24 08:37 UTC, Syldarion commented
As mentioned in the commit message of what I just added, an obvious solution had been staring me in the face all along. The for loop I added previously is gone, and performance seems in line with live.

2020-01-24 08:38 UTC, norraxx commented
I would to meet on discord.

2020-01-25 10:25 UTC, norraxx reviewed
Cosmetic changes.

2020-01-25 10:25 UTC, norraxx commented on scripts/updateLeagues.js
> +                if (leagueData.playerData == undefined) leagueData.playerData = [];
I don't like conditions like that, use brackets, it's ok to have 3 lines instead of 1.

2020-01-25 10:25 UTC, norraxx commented on scripts/updateLeagues.js
> +                    for (l in game.participants) {
use let

2020-01-25 10:25 UTC, norraxx commented on scripts/updateLeagues.js
> +                        for (category in leagueData.playerData) {
-//-

2020-01-25 10:25 UTC, norraxx commented on scripts/updateLeagues.js
> +                let categories = {};
you don't need it

2020-01-26 21:25 UTC, Brutus5000 approved these changes

2020-01-26 21:25 UTC, merged